### ISSUE TITLE
The proxy network is too slow after updating chinaroute

### ISSUE THREAD

**Issue by king6731253** [clowwindy/ChinaDNS#50]
I had deployed the OpenWRT on my router with ss+chinadns successfully.
Then I tried to set auto update of Chinaroute on it with CL like these:
#rm -f /etc/chinadns_chnroute.txt
#ln -s /etc/shadowsocks/ignore.list /etc/chinadns_chnroute.txt
#curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > /etc/shadowsocks/ignore.list

Then I found my proxy network got to be slow down significantly.
I checked the content of the updated ignore.list and it contains the update IPs from the apnic indeed.

How could this issue happen?

**Comment by clowwindy** [comment]
We only solve problems with ChinaDNS itself, please prove it's a problem of ChinaDNS itself, rather than your configuration. It's not fun to help everybody debug his own configuration. If you are unable to debug your network problem yourself, stick with standard configuration: https://sourceforge.net/p/openwrt-dist/wiki/DNS/
