### ISSUE TITLE
Reload chnroute file on SIGHUP?

### ISSUE THREAD

**Issue by hgl** [clowwindy/ChinaDNS#57]
So there is no need to restart chinadns if the chnroute file is updated.

**Comment by hgl** [comment]
Also would be great if chinadns could generate a pid file, so finding the process to send the signal would be easier.

**Comment by clowwindy** [comment]
/etc/init.d/chinadns restart

**Comment by hgl** [comment]
This could interrupt pending queries.

**Comment by hgl** [comment]
Wait a sec, i'm not using openwrt, maybe you did something special on that restart script? let me check the ipk file.

**Comment by hgl** [comment]
Oh, it's in the source code, and nope, it just stop & start chinadns. Would you be interested in merging if I take a stab at this feature?

**Comment by clowwindy** [comment]
Thanks. But no, since we don't update chnroute file that often. In practice, the only time that I want to restart chinadns is when I want to deploy a new binary.

**Comment by hgl** [comment]
APNIC's IP allocation changes pretty frequently actually. For example, Chinese IP range `103.48.144.0/22` is added on 2015-01-22, and is not included in chinadns' current chnroute file.

This feature could benefit users who manage the chnroute file themselves. (I have a cron job running checking that list daily.)

**Comment by hgl** [comment]
I wonder if some people's reporting about chinadns' returning foreign ips for domestic domains has something to do with the outdated chnroute file.

**Comment by clowwindy** [comment]
No, if the chnroutes list is incomplete, but if all your DNS servers are correctly located by the incomplete chnroutes list, we'll only have domestic IPs returned from foreign DNS unfiltered for domestic domains, which is not a big problem.

The cases to have some domestic domains resolved into foreign IPs are caused by current naive delay algorithm. By turning on `-m`, the delay will be replaced by an alternative strategy, and you can expect those problems to be fixed.

**Comment by hgl** [comment]
If the domain's name server doesn't respect `edns-client-subnet`, foreign ips are likely to be returned for requesting with a foreign dns. 

In the case of weibo.com, they don't support ECS (I confirm it with a patched dig). So outdated chnroute file is likely the cause.

By naive delay algorithm, do you mean that it's possible for a foreign DNS to return the records quicker (even with the delay) than a domestic DNS, thus its returned foreign ips gets accepted before the domestic DNS returns?

Kudos to the compression method, I guess it could eliminate the race condition introduced by the delay algorithm. Haven't gotten a chance to test it out, will update to the new version asap.

As for `SIGHUP`, I will stick with stop & start and see how it works. But in the case of auto updating, I guess it can it fail when cn ips are changed, and chinadns is auto restarted but while waiting some requests to return, so when they finally do, the new chinadns process simply discard them and the clients keep waiting forever.

**Comment by clowwindy** [comment]
As far as I know, at the moment, none of the popular websites support edns-client-subnet, including Google. So we haven't implemented edns-client-subnet in ChinaDNS yet.

The compression itself has nothing to do with the problem. In `-m` mode we simply turn off the delay, because the delay is no longer needed.

And for chnroutes, I guess you are not going to update chnroutes every hour, right? You can simply schedule chnroutes update at 3AM. Since you also need to reload your VPN route table, you don't want to be interrupted during the day.

**Comment by jedisct1** [comment]
They do, but only when the query comes from specific IP addresses.

Web sites and CDNs that want to receive queries with edns-client-subnet have to ask Google and Open DNS. Google and Open DNS will then manually add them, and it's common for authoritative servers to ignore edns-client-subnet when queries are not coming from the resolvers run by these companies. Sometimes because they don't want to make it easy for people to enumerate all the actual IPs they have, because that would weaken DDoS resistance.

The edns-client-subnet draft includes an opportunistic mode, where probes are sent. This is great, but unfortunately, nobody implemented this as far as I know.

**Comment by hgl** [comment]
That looks like the case.

If I request 8.8.8.8 about weibo.com directly, I get domestic ips. If I request 8.8.8.8 about weibo.com via a vpn (with edns-client-subnet set), I get foreign ips.

So looks like 8.8.8.8 doesn't honor edns-client-subnet itself.

**Comment by clowwindy** [comment]
@jedisct1

As for individuals, sounds that there's nothing we can do to utilize edns-client-subnet on our own servers.

Do Google and Open DNS offer a public list of the websites that have submitted for edns-client-subnet? I'm curious that how many popular websites from China have done that.

**Comment by jedisct1** [comment]
Only DNSPod (so all the websites using their DNS services I suppose) and Tencent as far as I know.
