### ISSUE TITLE
DNS 查询奇怪的卡死现象（没有超时强制结束机制？）

### ISSUE THREAD

**Issue by cokebar** [clowwindy/ChinaDNS#80]
VPS上使用pdnsd搭建DNS转发器 非标端口
由于自身网络原因 UDP方式的DNS查询有时候貌似丢包了无法查询成功
具体现象是使用dig命令进行连续的查询，数次之中会有那么一次卡住，长时间无结果返回，然后需要Ctrl+C强制终止命令或者等待其超时 然后再次查询时候正常 也就是 即使失败 如果重试 还是会成功
不过把这个挂到ChinaDNS上游服务器上 就出问题了 数次查询之后 出现一次卡住现象
接着后面全部的国外域名查询都会卡住 （重启chinadns后会重复上述现象）
加上-v运行chinadns 自卡住那次之后 没有任何来自vps的查询的信息（不是被filter了而是根本没有） 只有国内dns的response信息
难道是之前的查询一直卡在那里等待结果 过了非常久还不结束 导致后面的查询都进不来了？
觉得可以搞一个短超时值然后加个重试的过程 重试3次依然失败就强制结束不管了 避免这种不稳定带来的问题

**Comment by Pentiumluyu** [comment]
Your problem is the same as #78. It is caused by the queue_add function. https://github.com/clowwindy/ChinaDNS/blob/master/src/chinadns.c#L699
The queue_add function is not suitable for this kind of environment. Concurrency queries also suffer.
Modify this function yourself and create a pull request. Or just wait for the others to modify it.

**Comment by clowwindy** [comment]
Not designed for this setup
